import { Translations } from './types';

export const STRINGS: Translations = {
  appTitle: { en: 'PDF Master AI', ar: 'PDF ماستر الذكي' },
  uploadTitle: { en: 'Upload PDF Files', ar: 'رفع ملفات PDF' },
  uploadDesc: { en: 'Drag & drop files here, or click to select', ar: 'اسحب الملفات هنا أو انقر للاختيار' },
  merge: { en: 'Merge Selected', ar: 'دمج المحدد' },
  split: { en: 'Split', ar: 'تقسيم' },
  delete: { en: 'Delete', ar: 'حذف' },
  edit: { en: 'Edit', ar: 'تعديل' },
  save: { en: 'Save', ar: 'حفظ' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  summary: { en: 'Summarize', ar: 'تلخيص' },
  suggestTitle: { en: 'Suggest Title', ar: 'اقتراح عنوان' },
  ocr: { en: 'OCR / Extract Text', ar: 'استخراج النص' },
  processing: { en: 'Processing...', ar: 'جاري المعالجة...' },
  noFiles: { en: 'No files uploaded yet.', ar: 'لم يتم رفع أي ملفات بعد.' },
  pages: { en: 'Pages', ar: 'صفحات' },
  page: { en: 'Page', ar: 'صفحة' },
  aiTools: { en: 'AI Tools', ar: 'أدوات الذكاء الاصطناعي' },
  close: { en: 'Close', ar: 'إغلاق' },
  download: { en: 'Download', ar: 'تحميل' },
  back: { en: 'Back', ar: 'رجوع' },
  splitInstruction: { en: 'Select page range to split (e.g., 1-3)', ar: 'حدد نطاق الصفحات للتقسيم (مثال: 1-3)' },
  addText: { en: 'Add Text', ar: 'إضافة نص' },
  moveUp: { en: 'Move Left', ar: 'تحريك لليمين' }, 
  moveDown: { en: 'Move Right', ar: 'تحريك لليسار' },
  removePage: { en: 'Remove Page', ar: 'حذف الصفحة' },
  fileSaved: { en: 'File saved successfully', ar: 'تم حفظ الملف بنجاح' },
  error: { en: 'Error', ar: 'خطأ' },
  eraser: { en: 'Eraser', ar: 'ممحاة' },
  highlight: { en: 'Highlight', ar: 'قلم تمييز' },
  imageTool: { en: 'Add Image', ar: 'إضافة صورة' },
  undo: { en: 'Undo', ar: 'تراجع' },
  textTool: { en: 'Text', ar: 'نص' },
  moveTool: { en: 'Select / Move', ar: 'تحديد / تحريك' },
  clickToEdit: { en: 'Click page to edit content', ar: 'انقر على الصفحة لتعديل المحتوى' },
  saveChanges: { en: 'Apply Changes', ar: 'تطبيق التعديلات' },
  editorInstructions: { en: 'Select tool and click/drag on page.', ar: 'اختر أداة وانقر أو اسحب على الصفحة.' },
  enterText: { en: 'Type text here...', ar: 'اكتب النص هنا...' },
  add: { en: 'Add', ar: 'إضافة' },
  rotate: { en: 'Rotate 90°', ar: 'تدوير 90°' },
  loadSample: { en: 'Load Demo PDF', ar: 'تحميل نموذج PDF تجريبي' },
  copy: { en: 'Copy', ar: 'نسخ' },
  copied: { en: 'Copied!', ar: 'تم النسخ!' },
  applyTitle: { en: 'Apply Title', ar: 'تطبيق كاسم للملف' },
  rename: { en: 'Rename', ar: 'إعادة تسمية' },
  translate: { en: 'Translate', ar: 'ترجمة' },
  pageEditorTitle: { en: 'Visual Page Editor', ar: 'محرر الصفحة المرئي' },
  splitPages: { en: 'Split Document', ar: 'تقسيم المستند' },
  documentPages: { en: 'Document Pages', ar: 'صفحات المستند' },
  confirmDeleteDoc: { en: 'Are you sure you want to delete this document?', ar: 'هل أنت متأكد من حذف هذا المستند؟' },
  confirmDeletePage: { en: 'Are you sure you want to remove this page?', ar: 'هل أنت متأكد من حذف هذه الصفحة؟' },
  clearAll: { en: 'Clear Selection', ar: 'إلغاء التحديد' },
  selected: { en: 'selected', ar: 'محدد' },
  aiInsights: { en: 'AI Analysis & Intelligence', ar: 'تحليلات الذكاء الاصطناعي' },
  color: { en: 'Color', ar: 'اللون' },
  deleteElement: { en: 'Delete Element', ar: 'حذف العنصر' },
  exportPdf: { en: 'Export PDF', ar: 'تصدير PDF النهائي' },
  resize: { en: 'Resize', ar: 'تغيير الحجم' },
  editText: { en: 'Edit Text', ar: 'تعديل النص' },
  doubleClickToEdit: { en: 'Double click to edit text', ar: 'انقر مرتين لتعديل النص' },
  updateText: { en: 'Update Text', ar: 'تحديث النص' },
  liveNotice: { en: 'Elements remain editable & movable anytime until exported', ar: 'العناصر المضافة تبقى حرة وقابلة للتعديل والتحريك في أي وقت حتى التصدير' },
  unlockPageElements: { en: 'Unlock Original Elements', ar: 'تحرير عناصر الصفحة الأصلية' },
  unlocking: { en: 'Scanning & unlocking elements...', ar: 'جاري مسح وتحرير عناصر الصفحة...' },
  elementsUnlockedNotice: { en: 'Page elements are now unlocked! Double-click text to edit, press Delete to remove words, or drag to reposition.', ar: 'تم فك قفل عناصر الصفحة! انقر مرتين على أي كلمة لتعديلها، أو اضغط Delete لحذفها، أو اسحب لتحريكها.' },
  noElementsFound: { en: 'No native text found on this page. You can use the eraser tool and insert new elements.', ar: 'لم يتم العثور على نصوص قياسية قابلة للفك في هذه الصفحة. يمكنك استخدام أداة الممحاة وكتابة نصوص أو إضافة صور.' },
  unlockedBadge: { en: 'Unlocked Element', ar: 'عنصر أصلي حر' },
};